protect_pets_from: [PlayerDamage, EnvironmentalDamage, MobDamage]
tp_pets_between_worlds: true
allow_untaming_pets: true
total_pet_limit: -1
dog_limit: -1
cat_limit: -1
bird_limit: -1
tools:
  untame_pets: [SHEARS]
  get_owner: [BONE]
command_aliases:
  protected: [prot, p, pr]
  lost: [lostandfound, laf, lf, lost, l]
  dogs: [wolves, dog, wolf]
  cats: [cat, ocelot, ocelots]
  birds: [bird, parrots, parrot]
  horses: [horse]
  mules: [mule]
  llamas: [llama]
  donkeys: [donkey]
  help: [pls]
mysql:
  enable: false
  host: localhost
  port: 3306
  database: minecraft
  username: 'mcpluginuser'
  password: 'password'