name: TPPets
version: 1.0.0
description: Teleport pets around the map, but not in areas you don't want
load: POSTWORLD
author: GatheringExp
main: com.maxwellwheeler.plugins.tppets.TPPets
depend: [WorldEdit]
softdepend: [Vault]

commands:
  tpp:
    description: Base command for TPPets
    aliases: [teleportpets]
    usage: "Usage: /tpp [parrots/dogs/cats/protected/lost]"

permissions:
  tppets.*:
    description: Parent node of all tppets permissions.
    default: op
    children:
      tppets.bypassprotection: true
      tppets.tpanywhere: true
      tppets.protected: true
      tppets.lost: true
      tppets.dogs: true
      tppets.cats: true
      tppets.birds: true
  tppets.untameall:
    default: op
    description: Allows user to untame pets that they don't own.
  tppets.bypassprotection:
    default: op
    description: Allows user to damage pets that they don't own.
  tppets.bypasslimit:
    default: op
    description: Allows user to tame pets past the pet taming limit.
  tppets.tpanywhere:
    default: op
    description: Allows user to teleport pets into, and keep pets inside, protected regions.
  tppets.protected:
    default: op
    description: Allows user to set cuboid regions where pets are not allowed.
  tppets.lost:
    default: op
    description: Allows user to set cuboid regions where pets found in protected regions are sent.
  tppets.dogs:
    default: true
    description: Allows user to teleport their dogs to them.
  tppets.cats:
    default: true
    description: Allows user to teleport their cats to them.
  tppets.birds:
    default: true
    description: Allows user to teleport their birds to them.