protect_pets_from: [PlayerDamage, EnvironmentalDamage, MobDamage]
tp_pets_between_worlds: true
allow_untaming_pets: true
total_pet_limit: -1
dog_limit: -1
cat_limit: -1
bird_limit: -1
command_aliases:
  protected: [prot, p, pr]
  lost: [lostandfound, laf, lf, lost, l]
  dogs: [wolves, dog, wolf]
  cats: [cat, ocelot, ocelots]
  birds: [bird, parrots, parrot]
  help: [pls]
mysql:
  enable: true
  host: localhost
  port: 3306
  database: minecraft
  username: 'mcpluginuser'
  password: 'password'