protect_pets_from: [Player, EnvironmentalDamage, MobDamage]
tp_pets_between_worlds: true
command_aliases:
  restricted: [restrict, rest, r]
  lost: [lostandfound, laf, lf, lost, l]
  dogs: [wolves, dog, wolf]
  cats: [cat, ocelot, ocelots]
  birds: [bird, parrots, parrot]
  help: [pls]