name: TPPets
version: 0.9.0
description: Teleport pets to certain areas of the map
load: POSTWORLD
author: GatheringExp
main: com.maxwellwheeler.plugins.tppets.TPPets
depend: [WorldEdit]

commands:
  tpp:
    description: Base command for TPPets
    aliases: [teleportpets]
    usage: "Usage: /tpp [parrots/dogs/cats/restricted/lost]"
  generate-tamed-dogs:
    description: Testing only
  tp-forward:
    description: Testing only

permissions:
  tppets.*:
    description: Allows teleportation of every pet, and allows teleportation in restricted areas.
    default: op
    children:
      tppets.bypassprotection: true
      tppets.tpanywhere: true
      tppets.restricted: true
      tppets.lost: true
      tppets.dogs: true
      tppets.cats: true
      tppets.birds: true
  tppets.bypassprotection:
    default: op
    description: Allows user to damage pets that they don't own.
  tppets.tpanywhere:
    default: op
    description: Allows user to teleport pets in restricted regions.
  tppets.restricted:
    default: op
    description: Allows user to set cuboid regions where pets are not allowed.
  tppets.lost:
    default: op
    description: Allows user to set cuboid regions where pets are teleported if they are caught in a no-pets area.
  tppets.dogs:
    default: true
    description: Allows teleporting dogs.
  tppets.cats:
    default: true
    description: Allows teleporting cats.
  tppets.birds:
    default: true
    description: Allows teleporting parrots.